version: '3'
name: 'goserv'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    networks:
      - container-network

  webserver:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - container-network
    volumes:
      - cert-volume:/etc/letsencrypt/
    depends_on:
      - webapp

networks:
  container-network:

volumes:
  cert-volume:
